### ISSUE TITLE
There is no file like /home/physics/.elisa/limbdarkening/ld/lin.bolometric.p00.csv.

### ISSUE THREAD

**Issue by AstrophysicsAndPython** [mikecokina/elisa#10]
I made a `conda` environment
```
conda create env -n elisa python=3.7
```
I installed ELISa
```
/home/physics/anaconda3/env/elisa/bin/pip3 install elisa
```
After that I followed the light curve tutorial ([here](https://github.com/mikecokina/elisa/blob/dev/jupyter_tutorials/demo06-light_curves.ipynb)). However, when I run the following code, it gives me this above error
```
phases, fluxes = o.observe.lc(
    from_phase=-0.6,
    to_phase=0.6,
    phase_step=0.01,
    normalize=True  # this will produce observations normalized to 1
)
```

**Comment by mirofedurco** [comment]
Hi,

thanks for bringing out this issue. Directory '.elisa' is supposed to contain all necessary limb-darkening and atmosphere tables. As stated in [readme.rst](https://github.com/mikecokina/elisa/blob/dev/README.rst) for our latest release 0.5.1, you need to download them into your .elisa directory or any other custom location that would be then specified in your conguration file (see detailed instructions in the [readme.rst](https://github.com/mikecokina/elisa/blob/dev/README.rst)). 

As for the version 0.6 currently in the development that can be installed using command `pip install git+https://github.com/mikecokina/elisa.git@dev`, the necessary tables are downloaded automatically during the first use of elisa `.py` script. If the automatic installation will not happen inside the jupyter notebook, try to simply `import elisa` in the python console within your virtual environment with the fresh installation ELISa or just launch simple `.py` script using elisa. The  manual process described for the version 0.5.1 is also viable in the newer version as well.

I hope this instruction helps. In case of any other issues, feel free to contact us.

Sincerely,
Miro

**Comment by AstrophysicsAndPython** [comment]
Hi, thank you for your response. I did find some files and I did download them to the `.elisa/limbdarkening/ld/` directory, but I can't seem to find the file `lin.Generic.Bessell.B.p00.csv`. It doesn't show up even in search

![image](https://user-images.githubusercontent.com/73373619/149609488-6d63991c-d4b3-4720-9fd5-86b684ae829a.png)

**Comment by AstrophysicsAndPython** [comment]
I will try the other method shortly.

Cheers!

**Comment by mirofedurco** [comment]
Hi

when you download the ld tables from [here](https://mega.nz/file/7U0h3RpC#ZxAGflTglX3JGOmTS0C9S8WF64bnibRyGTeNJG0eZyQ), the file in question is there. Remember to extract it into the default hidden configuration folder $HOME/.elisa/limb_darkening/ (not regular visible folder elisa, as you seem to search for the missing file there). 

Miro

**Comment by mikecokina** [comment]
Closing inactive issues.
