### ISSUE TITLE
The estimated mass of the secondary component is not according to given mass ratio of the system and mass of the primary component

### ISSUE THREAD

**Issue by kh-kr** [mikecokina/elisa#12]
Hi,

I am trying to fit a TESS light curve of an eclipsing binary. The parameter list is as follows

lc_initial = {
    'system': {
        # setting a reasonable expected starting value and range of the parameters 
        'inclination': {  
            'value': 72.0,
            'fixed': False,
            'min': 65,
            'max': 90,
            'unit': u.deg
        },
        'eccentricity': {  
            'value': 0.01,
            'fixed': False,
            'min': 0.0,
            'max': 0.3,
        },
        # mass ratio is much more acurately determined from RV fit, therefore we will keep it fixed during initial LC fit
        'mass_ratio': {
            'value': 0.45,
            'fixed': False,
            'min': 0.3,
            'max': 0.6,
        },  
        'argument_of_periastron': {
            'value': 90,
            'fixed': False,
            'min': 0,
            'max': 360,
            'unit': u.deg
        },  
        # this parameter is constrained to orbital inclination via the `asini` derived during the RV fit
        'semi_major_axis': {
            'constraint': '11.2 / sin(radians(system@inclination))',  # IMPORTANT: only variable model parameters can be used to define a constraint
            'unit': u.solRad
        },  
        'period': {
            'value':1.6,
            'fixed': True,
            'unit': u.d
        },
        # this parameter allows for the presence of the third light
        'additional_light': {
            'value': 0.0,
            'fixed': False,
            'min': 0.0,
            'max': 0.5,
        },
        # accounting for imprecision of the ephemeris
        'phase_shift': {
            'value': 0,
            'fixed': False,
            'min': -0.02,
            'max': 0.02,
        },
        # 'primary_minimum_time': {
        #     'value': 54953.900507000006,
        #     'fixed': True,
        #     'unit': u.d,
        # }, time of primary minimum should be supplied only in case when LCData contain light curves in BJD 
        # instad of photometric phase 
    },
    'primary': {
        # initial run will keep the primary effective temperature fixed on the value derived in the literature (Armstrong et al. 2013, MNRAS, 437, 4, 3473–3481)
        't_eff': {
            'value': 7500.0,
            'fixed': False,
            'min': 7000,
            'max': 7500,
            'unit': u.K
        },  # fixed to value found in literature
        'surface_potential': {
            'value': 3.5,
            'fixed': False,
            'min': 3.0,
            'max': 10.0,
        },
        'mass': {
            'value': 1.45,
            'fixed': False,
            'min': 1.3,
            'max': 1.7,
            'unit': u.solMass
        },
        # albedos and gravity darkening factors will stay fixed for the initial run
        'albedo': {
            'value': 1.0,
            'fixed': True
        },
        'gravity_darkening': {
            'value': 1.0,
            'fixed': True
        },
        # assuming synchronized rotation at periastron
        "synchronicity": {
            "value": 1.00,
            "constraint": "(1 + system@eccentricity)**2 / (1 - system@eccentricity**2)**(3.0/2.0)",
            "unit": None
        },
        "metallicity": {
            "value": 0.0,
            "fixed": True,
            "unit": None
        }
    },
    'secondary': {
        't_eff': {
            'value': 11500,
            'fixed': False,
            'min': 9000.0,
            'max': 20000.0,
            'unit': u.K
        },
        'surface_potential': {
            'value': 7.1,
            'fixed': False,
            'min': 6.0,
            'max': 10.0,
        },
        'albedo': {
            'value': 1.0,
            'fixed': True
        },
        'gravity_darkening': {
            'value': 1.0,
            'fixed': True
        },
        "synchronicity": {
            "value": 1.00,
            "constraint": "(1 + system@eccentricity)**2 / (1 - system@eccentricity**2)**(3.0/2.0)",
            "unit": None
        },
        "metallicity": {
            "value": 0.0,
            "fixed": True,
            "unit": None
        }
    }
}

And the fitted light curve is shown below
![Screenshot from 2022-04-03 11-47-31](https://user-images.githubusercontent.com/79892737/161414530-6184ed73-cf41-4f7a-8f06-40f636152832.png)

My doubt is, I have given the mass of the primary component and also the mass ratio of the system. But the derived mass of the secondary component by Elisa is not according to the mass ratio of the system and the mass of the primary component.

Given parameters: mass ratio (system) = 0.45
                              mass (primary component) = 1.45 solar_mass
obtained parameters by Elisa: mass (secondary component) = 2.657 solar_mass

Why is  it happening, can anyone help me with this?

Thanks!
Khushboo

**Comment by mirofedurco** [comment]
Hi,

parameters for the light curve fitting procedure can be supplied either in `standard` or `community` format. In standard format, masses of the both components are supplied whereas in `community` format, mass ratio along with the semi major axis have to be included. The full list of available input parameter combinations is included in [demo12](https://github.com/mikecokina/elisa/blob/dev/jupyter_tutorials/demo12-lc_fitting.ipynb) (Cell 9).

At this moment, Elisa does not support other input combinations of parameters such as you mentioned here (mass_ratio + mass of the primary). Since It does not seem like you have a prior knowledge about the component masses, I recommend you to use `community` format, i.e. switch to a parameter combination including mass ratio and semi major axis. In your case that means that you should remove parameter primary mass and try it again.

Thank you for pointing out this issue I will try to make adjustments that will raise a warning if user will try to use parameter combinations that do not adhere to our allowed formats.

With regards,
Miro
