### ISSUE TITLE
Extend the ld tables to include WD

### ISSUE THREAD

**Issue by nagarajvernekar30** [mikecokina/elisa#16]
Hello, I was trying to model a binary system with a main sequence star and a low mass white dwarf star (0.03 R and 15000 K). While trying to model this, I receive an error saying that these parameters are out of bound. Could you suggest what tables should I include to model such systems

**Comment by mikecokina** [comment]
Hi, sorry for late response. Such feature is currently not supported. However, you can use black body instead. Take a look on [this ](https://github.com/mikecokina/elisa/blob/dev/jupyter_tutorials/demo14-atmosphere_models%26custom_limb-darkening_coefficients.ipynb) tutorial notebook.
