### ISSUE TITLE
spot discretization factor bug

### ISSUE THREAD

**Issue by fredy402** [mikecokina/elisa#3]
Discretization factor for spots on secondary component are not scaled to the discretization factor of the rest of the secondary surface. Issue happens when secondary discretization factor is derived from primary discretization factor (not explicitly set by user).
![Spectacle n23807](https://user-images.githubusercontent.com/40992155/70524371-47d42400-1b45-11ea-8d81-a90bd075e936.png)

**Comment by mikecokina** [comment]
Is it resolved?

**Comment by fredy402** [comment]
solved
