### ISSUE TITLE
Missing data file from demo data

### ISSUE THREAD

**Issue by 5-5Men** [mikecokina/elisa#7]
Hello!  KIC04851217.lc.pulse_removed.dat seems to be missing from the demo data folder.  Thanks, have just downloaded this interesting package as saw it mentioned in a recent RAA paper and looking forward to using it.  Just working through the demos.

**Comment by mirofedurco** [comment]
Hello @5-5Men! Sorry for the inconvenience, the file in question is was added. Thank you for pointing out this issue.
