### ISSUE TITLE
I have a  problem with TESS data

### ISSUE THREAD

**Issue by MohammadEftekhar** [mikecokina/elisa#8]
I would be grateful if you could give me an example of working with‌ TESS data.

**Comment by mirofedurco** [comment]
Hi,

ELISa enables to load observational data from various sources into a data container called [LCData](https://github.com/mikecokina/elisa/blob/44c6dc5cf86a4446c926243e0107a8e316bef374/src/elisa/analytics/dataset/base.py#L260) where you can insert any light curve observations stored in column tabulated data (eg. datafile with columns consisting of JD, flux and flux error).  See this [demo](https://github.com/mikecokina/elisa/blob/dev/jupyter_tutorials/demo10-datasets.ipynb) to learn how to initialize LCData container. Afterwards, such container can be used as an input to your LC fitting routine (see this [demo](https://github.com/mikecokina/elisa/blob/dev/jupyter_tutorials/demo12-lc_fitting.ipynb)).

If this was not helpful, please contact us for further info.


With regards,
Miro

**Comment by MohammadEftekhar** [comment]
Thank you mirofedurco

I Read my lc.fits data as:

hdu = fits.open("/home/m/Desktop/Data/Binaries/KIC 8382182/tess2019226182529-s0015-0000000273038330-0151-s_lc.fits")
time = hdu[1].data['TIME']
flux = hdu[1].data['PDCSAP_FLUX'] # values with non-zero quality are nan or zero'ed
ferr = hdu[1].data['PDCSAP_FLUX_ERR']

could you please tell me how to initialize LCData container?

**Comment by mirofedurco** [comment]
Hi,

thank you for the example. What seems to be the problem is that your observations contain one or multiple NaNs which ELISa for now evaluates as invalid input. Also, data directly from the TESS archive are listed in electron count (e/s) which we recommend to transform to the normalized flux. Based on these recommendations, you should use script such as this:

```
from astropy.io import fits
import matplotlib.pyplot as plt
import numpy as np

from elisa import LCData, units

fits_file = "/home/m/Desktop/Data/Binaries/KIC 8382182/tess2019226182529-s0015-0000000273038330-0151-s_lc.fits"
hdu = fits.open(fits_file)

time = hdu[1].data['TIME']
flux = hdu[1].data['PDCSAP_FLUX']  # values with non-zero quality are nan or zero'ed
ferr = hdu[1].data['PDCSAP_FLUX_ERR']

#  filtering out NaNs
not_nan_x = ~np.isnan(time)
not_nan_y = ~np.isnan(flux)
not_nan = np.logical_and(not_nan_x, not_nan_y)

time = time[not_nan]
flux = flux[not_nan]
ferr = ferr[not_nan]

# normalization from e/s to normalized flux
mean_flux = flux.mean()
flux /= mean_flux
ferr /= mean_flux

# initializating the container
tess = LCData(x_data=time,
              y_data=flux,
              y_err=ferr,
              x_unit=units.d,
              y_unit=units.dimensionless_unscaled)

# visualization of the results
tess.plot.display_observation()
```

Let us know if you have any further issues.

With regards,
Miro

**Comment by MohammadEftekhar** [comment]
Hi Miro,

Thank you for your kindness and guidance. It works now.
I hope you have been keeping safe!
Mohammad
